// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsCoreOrchestration "github.com/acme-kuetix/acme-std-core/modules/core/orchestration/transitions"
	transitionsCoreUtils "github.com/acme-kuetix/acme-std-core/modules/core/utils/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["core/orchestration"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"core/orchestration"+"/"+"orchestration", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "orchestration", Impl: transitionsCoreOrchestration.NewOrchestrationTransitions() }})
	}
	di.DependencyInjection["core/utils"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"core/utils"+"/"+"utils", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "utils", Impl: transitionsCoreUtils.NewUtilsTransitions() }})
	}
}
