// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/engine/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"core/orchestration": {
			"orchestration": {
				"RunWorkflow": {
					GoModule: "github.com/acme-kuetix/acme-std-core",
					ModulePath: "modules",
					FilePath: "modules/core/orchestration/transitions/orchestration.go",
					Namespace: "orchestration",
					Class: "core/orchestration",
					Name: "RunWorkflow",
					NumIn: 2,
					NumOut: 1,
					ArgTypes: []string{"*workflow.WorkerSessionContext", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"p", "name"},
					ReturnNames: []string{"r"},
				},
				"RunFeature": {
					GoModule: "github.com/acme-kuetix/acme-std-core",
					ModulePath: "modules",
					FilePath: "modules/core/orchestration/transitions/orchestration.go",
					Namespace: "orchestration",
					Class: "core/orchestration",
					Name: "RunFeature",
					NumIn: 2,
					NumOut: 1,
					ArgTypes: []string{"*workflow.WorkerSessionContext", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"p", "name"},
					ReturnNames: []string{"r"},
				},
			},
		},
		"core/utils": {
			"utils": {
				"ToInt": {
					GoModule: "github.com/acme-kuetix/acme-std-core",
					ModulePath: "modules",
					FilePath: "modules/core/utils/transitions/utils.go",
					Namespace: "utils",
					Class: "core/utils",
					Name: "ToInt",
					NumIn: 1,
					NumOut: 1,
					ArgTypes: []string{"interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"v"},
					ReturnNames: []string{"r"},
				},
				"ParseTaxTemplateIds": {
					GoModule: "github.com/acme-kuetix/acme-std-core",
					ModulePath: "modules",
					FilePath: "modules/core/utils/transitions/utils.go",
					Namespace: "utils",
					Class: "core/utils",
					Name: "ParseTaxTemplateIds",
					NumIn: 1,
					NumOut: 1,
					ArgTypes: []string{"interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"v"},
					ReturnNames: []string{"r"},
				},
				"SetValue": {
					GoModule: "github.com/acme-kuetix/acme-std-core",
					ModulePath: "modules",
					FilePath: "modules/core/utils/transitions/utils.go",
					Namespace: "utils",
					Class: "core/utils",
					Name: "SetValue",
					NumIn: 2,
					NumOut: 1,
					ArgTypes: []string{"string", "interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"key", "value"},
					ReturnNames: []string{"r"},
				},
				"GetValue": {
					GoModule: "github.com/acme-kuetix/acme-std-core",
					ModulePath: "modules",
					FilePath: "modules/core/utils/transitions/utils.go",
					Namespace: "utils",
					Class: "core/utils",
					Name: "GetValue",
					NumIn: 1,
					NumOut: 1,
					ArgTypes: []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames: []string{"key"},
					ReturnNames: []string{"r"},
				},
			},
		},
	})
}

